export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_USER_CALENDAR_REQUEST = "FETCH_USER_CALENDAR_REQUEST";
export const FETCH_USER_CALENDAR_SUCCESS = "FETCH_USER_CALENDAR_SUCCESS";
export const FETCH_USER_CALENDAR_FAILURE = "FETCH_USER_CALENDAR_FAILURE";

export const FETCH_USER_API_TOKEN_REQUEST = "FETCH_USER_API_TOKEN_REQUEST";
export const FETCH_USER_API_TOKEN_SUCCESS = "FETCH_USER_API_TOKEN_SUCCESS";
export const FETCH_USER_API_TOKEN_FAILURE = "FETCH_USER_API_TOKEN_FAILURE";
export const FETCH_USER_GRAPH_TOKEN_REQUEST = "FETCH_USER_GRAPH_TOKEN_REQUEST";
export const FETCH_USER_GRAPH_TOKEN_SUCCESS = "FETCH_USER_GRAPH_TOKEN_SUCCESS";
export const FETCH_USER_GRAPH_TOKEN_FAILURE = "FETCH_USER_GRAPH_TOKEN_FAILURE";
