export const POST_USER_LOGIN_REQUEST = "POST_USER_LOGIN_REQUEST";
export const POST_USER_LOGIN_SUCCESS = "POST_USER_LOGIN_SUCCESS";
export const POST_USER_LOGIN_FAILURE = "POST_USER_LOGIN_FAILURE";

export const GET_USER_SESSION_FAILURE = "GET_USER_SESSION_FAILURE";
export const GET_USER_SESSION_REQUEST = "GET_USER_SESSION_REQUEST";
export const GET_USER_SESSION_SUCCESS = "GET_USER_SESSION_SUCCESS";

export const POST_USER_REGISTER_NEW_ORGANIZAITON_REQUEST =
  "POST_USER_REGISTER_NEW_ORGANIZAITON_REQUEST";
export const POST_USER_REGISTER_NEW_ORGANIZAITON_SUCCESS =
  "POST_USER_REGISTER_NEW_ORGANIZAITON_SUCCESS";
export const POST_USER_REGISTER_NEW_ORGANIZAITON_FAILURE =
  "POST_USER_REGISTER_NEW_ORGANIZAITON_FAILURE";

export const POST_USER_REGISTER_EXISTING_ORGANIZAITON_REQUEST =
  "POST_USER_REGISTER_EXISTING_ORGANIZAITON_REQUEST";
export const POST_USER_REGISTER_EXISTING_ORGANIZAITON_SUCCESS =
  "POST_USER_REGISTER_EXISTING_ORGANIZAITON_SUCCESS";
export const POST_USER_REGISTER_EXISTING_ORGANIZAITON_FAILURE =
  "POST_USER_REGISTER_EXISTING_ORGANIZAITON_FAILURE";

export const GET_USER_ORGANIZATIONS_REQUEST = "GET_USER_ORGANIZATIONS_REQUEST";
export const GET_USER_ORGANIZATIONS_SUCCESS = "GET_USER_ORGANIZATIONS_SUCCESS";
export const GET_USER_ORGANIZATIONS_FAILURE = "GET_USER_ORGANIZATIONS_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_ALL_TAGS_REQUEST = "GET_ALL_TAGS_REQUEST";
export const GET_ALL_TAGS_SUCCESS = "GET_ALL_TAGS_SUCCESS";
export const GET_ALL_TAGS_FAILURE = "GET_ALL_TAGS_FAILURE";

export const POST_TICKETS_NEW_TICKET_REQUEST =
  "POST_TICKETS_NEW_TICKET_REQUEST";
export const POST_TICKETS_NEW_TICKET_SUCCESS =
  "POST_TICKETS_NEW_TICKET_SUCCESS";
export const POST_TICKETS_NEW_TICKET_FAILURE =
  "POST_TICKETS_NEW_TICKET_FAILURE";

export const POST_EXPERTISE_TAGS_REQUEST = "POST_EXPERTISE_TAGS_REQUEST";
export const POST_EXPERTISE_TAGS_SUCCESS = "POST_EXPERTISE_TAGS_SUCCESS";
export const POST_EXPERTISE_TAGS_FAILURE = "POST_EXPERTISE_TAGS_FAILURE";

export const GET_EXPERTISE_TAGS_REQUEST = "GET_EXPERTISE_TAGS_REQUEST";
export const GET_EXPERTISE_TAGS_SUCCESS = "GET_EXPERTISE_TAGS_SUCCESS";
export const GET_EXPERTISE_TAGS_FAILURE = "GET_EXPERTISE_TAGS_FAILURE";

export const GET_TICKETS_REQUEST = "GET_TICKETS_REQUEST";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_FAILURE = "GET_TICKETS_FAILURE";

export const PUT_TICKETS_ASSIGN_REQUEST =
  "PUT_TICKETS_ASSIGN_REQUEST";
export const PUT_TICKETS_ASSIGN_SUCCESS =
  "PUT_TICKETS_ASSIGN_SUCCESS";
export const PUT_TICKETS_ASSIGN_FAILURE =
  "PUT_TICKETS_ASSIGN_FAILURE";

export const PUT_TICKETS_AUTO_ASSIGN_REQUEST =
  "PUT_TICKETS_AUTO_ASSIGN_REQUEST";
export const PUT_TICKETS_AUTO_ASSIGN_SUCCESS =
  "PUT_TICKETS_AUTO_ASSIGN_SUCCESS";
export const PUT_TICKETS_AUTO_ASSIGN_FAILURE =
  "PUT_TICKETS_AUTO_ASSIGN_FAILURE";

export const GET_USER_ALL_REQUEST = "GET_USER_ALL_REQUEST";
export const GET_USER_ALL_SUCCESS = "GET_USER_ALL_SUCCESS";
export const GET_USER_ALL_FAILURE = "GET_USER_ALL_FAILURE";

export const PUT_USER_APPROVED_REQUEST = "PUT_USER_APPROVED_REQUEST";
export const PUT_USER_APPROVED_SUCCESS = "PUT_USER_APPROVED_SUCCESS";
export const PUT_USER_APPROVED_FAILURE = "PUT_USER_APPROVED_FAILURE";

export const GET_PERMISSIONS_ALL_REQUEST = "GET_PERMISSIONS_ALL_REQUEST";
export const GET_PERMISSIONS_ALL_SUCCESS = "GET_PERMISSIONS_ALL_SUCCESS";
export const GET_PERMISSIONS_ALL_FAILURE = "GET_PERMISSIONS_ALL_FAILURE";

export const GET_TECHNICIANS_ASSIGN_REQUEST = "GET_TECHNICIANS_ASSIGN_REQUEST";
export const GET_TECHNICIANS_ASSIGN_SUCCESS = "GET_TECHNICIANS_ASSIGN_SUCCESS";
export const GET_TECHNICIANS_ASSIGN_FAILURE = "GET_TECHNICIANS_ASSIGN_FAILURE";

export const PUT_PERMISSIONS_REQUEST = "PUT_PERMISSIONS_REQUEST";
export const PUT_PERMISSIONS_SUCCESS = "PUT_PERMISSIONS_SUCCESS";
export const PUT_PERMISSIONS_FAILURE = "PUT_PERMISSIONS_FAILURE";

export const POST_TAGS_REQUEST = "POST_TAGS_REQUEST";
export const POST_TAGS_SUCCESS = "POST_TAGS_SUCCESS";
export const POST_TAGS_FAILURE = "POST_TAGS_FAILURE";

export const DELETE_TAG_REQUEST = "DELETE_TAG_REQUEST";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const DELETE_TAG_FAILURE = "DELETE_TAG_FAILURE";

export const PUT_TAGS_REQUEST = "PUT_TAGS_REQUEST";
export const PUT_TAGS_SUCCESS = "PUT_TAGS_SUCCESS";
export const PUT_TAGS_FAILURE = "PUT_TAGS_FAILURE";

export const PUT_TAG_CATEGORIES_REQUEST = "PUT_TAG_CATEGORIES_REQUEST";
export const PUT_TAG_CATEGORIES_SUCCESS = "PUT_TAG_CATEGORIES_SUCCESS";
export const PUT_TAG_CATEGORIES_FAILURE = "PUT_TAG_CATEGORIES_FAILURE";

export const PUT_TICKET_PRIORITY_REQUEST = "PUT_TICKET_PRIORITY_REQUEST";
export const PUT_TICKET_PRIORITY_SUCCESS = "PUT_TICKET_PRIORITY_SUCCESS";
export const PUT_TICKET_PRIORITY_FAILURE = "PUT_TICKET_PRIORITY_FAILURE";

export const POST_TAG_CATEGORY_REQUEST = "POST_TAG_CATEGORY_REQUEST";
export const POST_TAG_CATEGORY_SUCCESS = "POST_TAG_CATEGORY_SUCCESS";
export const POST_TAG_CATEGORY_FAILURE = "POST_TAG_CATEGORY_FAILURE";

export const GET_TAG_CATEGORIES_REQUEST = "GET_TAG_CATEGORIES_REQUEST";
export const GET_TAG_CATEGORIES_SUCCESS = "GET_TAG_CATEGORIES_SUCCESS";
export const GET_TAG_CATEGORIES_FAILURE = "GET_TAG_CATEGORIES_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
